services:
  frontend:
    container_name: frontend-prod
    image: frontend-prod
    build:
      context: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - api

  api:
    container_name: api-prod
    image: api-prod
    build: ./api
    ports:
      - 3000:3000
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    entrypoint: ["java", "-jar", "app.jar", "--spring.profiles.active=staging"]

  reverse-proxy:
    container_name: reverse-proxy-prod
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - frontend
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf