spring.application.name=demo

server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/mms
spring.datasource.username=postgres
spring.datasource.password=HayounZ2002/
spring.jpa.generate-ddl=true

# Configuration upload de fichiers
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.dir=uploads
