spring.application.name=demo

server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/mms
spring.datasource.username=postgres
spring.datasource.password=HayounZ2002/
spring.jpa.generate-ddl=true
